### ISSUE TITLE
AVIM - Firefox - Tự bỏ hết dấu khi comment trên Facebook

### ISSUE THREAD

**Issue by thuandt** [1ec5/avim#105]
Mình dùng AVIM trên Firefox đã nhiều năm nay và không có vấn đề gì cả.

Sau bản cập nhật vừa rồi *.5.0.3, khi gõ Tiếng Việt bằng AVIM trên Facebook mình bị hiện tượng như sau: khi gõ comment một post trên facebook, gõ tiếng việt có dấu bình thường, nhưng nếu đánh space rồi backspace lại thì nó tự strip hết dấu đi chỉ còn Tiếng Việt không dấu. Trước khi cập nhật mình không bị vậy.

Hiện tượng này chỉ xảy ra khi comment còn post bài mới thì vẫn bình thường.

Mình sử dụng Facebook giao diện Tiếng Anh, Firefox 33.0, Hệ điều hành: Ubuntu 14.04. Mình dùng khá nhiều Addons, tuy nhiên với phiên bản trước của AVIM thì không bị vậy.

**Comment by 1ec5** [comment]
Vấn đề này đã trở lại: #171.
