### ISSUE TITLE
ff 58

### ISSUE THREAD

**Issue by lucky0511** [1ec5/avim#185]
nếu có thể bạn update cho ff 58 dev với nhé, cảm ơn bạn, chúc bạn nhiều sức khỏe!

**Comment by 1ec5** [comment]
Rất tiếc là Firefox 58 trở lên không còn tương thích với các phần mở rộng như AVIM, chỉ có tương thích với các WebExtension rất đơn giản. Tôi đang cố gắng tìm cách để viết lại phần mở rộng dùng WebExtension, nhưng điều này rất khó vì các hạn chế của tính năng đó. Xin theo dõi công việc này tại #141. Cám ơn sự kiên nhẫn của bạn!
