### ISSUE TITLE
Hỗ trợ chính thức cho PaleMoon

### ISSUE THREAD

**Issue by hoper-a11y** [1ec5/avim#201]
Bạn ơi bạn có thể thêm hỗ trợ chính thức cho PaleMoon được không bạn? Hiện giờ thì mình cài avim vào PaleMoon vẫn được nhưng nó hiện thông báo là: Avim was not designed for PaleMoon. It may not function or cease to function rồi dẫn tới link này: https://forum.palemoon.org/viewtopic.php?f=46&t=23697

Mình sử dụng avim rất nhiều vì mình chỉ cần gõ trong trình duyệt còn máy thì cũng không cài ứng dụng Office nào. Mình hiện chỉ sử dụng mỗi cái trình duyệt PaleMoon này vì nó tương thích rất tốt với các tiện ích cũ của Firefox. Mong bạn xem xét hỗ trợ chính thức cho PaleMoon. Cảm ơn bạn.

**Comment by hoper-a11y** [comment]
Mình thấy chắc là bạn không quan tâm đâu, thôi thì mình đóng ticket này lại vậy. Cảm ơn bạn vì đã phát triển AVIM.

**Comment by 1ec5** [comment]
Xin lỗi, mình hơi bận tuần nay, không thấy lời yêu cầu này hôm kia. Mình đã chắc chắn rằng AVIM hỗ trợ Pale Moon từ lâu rồi, nhưng không biết rằng nó có ID ứng dụng khác với Firefox cho đến khi bạn báo cáo lỗi này. Mình vừa thêm ID ứng dụng của Pale Moon trong c7bc3116b2fd4e2e66318f610e3a1006608338f8, và phiên bản sau sẽ hỗ trợ trình duyệt này.

**Comment by 1ec5** [comment]
Thay đổi này được phát hành trong [v5.8.3](https://github.com/1ec5/avim/releases/tag/v5.8.3). Xin bạn thử xem. Mình không thể thử trong các phiên bản Pale Moon mới vì trình duyệt đó không có chính thức hỗ trợ máy macOS của mình. Nếu bạn vẫn gặp cảnh báo này thì mình sẽ xem lại.
